### ISSUE TITLE
remote data search

### ISSUE THREAD

**Issue by cethol** [harshzalavadiya/react-multi-select-component#105]
Hi, thanks for making this component so beautiful, but i have some problem when load thousands data into this component, it makes slow. Please suggest how to make it possible to load data when it match with the search term. Thank you!

**Comment by harshzalavadiya** [comment]
@cethol, as of now dropdown component does not have any kind of virtual renderer in order to keep this compact

but this should not happen in most of scenarios because you could preferabally trim down results to 10-20 based on query because by implementating custom `filterOptions`

I would recommend going with https://react-select.com/async in autocomplete beacuse they have very simple implementation just for this kinda scenario

**Comment by cethol** [comment]
Hi, thanks for the answer. but can you give me an example how to use `filterOptions`? because i always get this error.
![image](https://user-images.githubusercontent.com/2105802/90782729-65d76280-e329-11ea-9bbd-f9baa135ff64.png)

**Comment by harshzalavadiya** [comment]
Minimal Example
https://github.com/harshzalavadiya/react-multi-select-component#-custom-filter-logic

react-multi-select-component's Fuzzy Match Implementation
https://github.com/harshzalavadiya/react-multi-select-component/blob/master/src/lib/fuzzy-match-utils.tsx#L23-L55

**Comment by cethol** [comment]
Thank you for your answer.
