### ISSUE TITLE
performance issues

### ISSUE THREAD

**Issue by ankiiitraj** [harshzalavadiya/react-multi-select-component#208]
When there are lot of option, operations are slow like on clicking the select, it takes time to load the dropdown! Search also becomes slow.

This might be due to rendering lot of data. 

Proposed solution:
We can have shallowOptionCount, which will limit the amount of options to be rendered at once on the dropdown. And search will help get the more results!

I have 3000+ option and I'm having these throttling issues!

**Comment by harshzalavadiya** [comment]
@ankiiitraj 

IMHO, I think implementing lazy options based on search query might be a way to go instead of loading 3k+ items, in most scenario loading 3000+ options is never a good idea

I know virtual scrolling can be one way to solve this problem, but my only concern is that will make bundle size big and that's a very big issue

https://react-select.com/async
https://www.npmjs.com/package/react-select-virtualized
