### ISSUE TITLE
component not working in IE getting css polyfill error though i installed it in  project

### ISSUE THREAD

**Issue by ramkumar93v** [harshzalavadiya/react-multi-select-component#26]

**Comment by harshzalavadiya** [comment]
Hi @ramkumar93v,

If you are facing styles not being rendered properly then it will be due to lack of css variables support in IE

If you have polyfilled application properly then functionally should work just fine see screenshot below.

![IE11-Polyfill](https://user-images.githubusercontent.com/5774849/81940257-07596480-9615-11ea-881d-f65a8f87239b.gif)

p.s. just in case if anyone needs to polyfill this manually

```html
<script src="https://cdn.polyfill.io/v3/polyfill.min.js?features=default,Array.prototype.includes,Array.prototype.find"></script>
```

Closing this since as of now there's no plan to directly support IE
