### ISSUE TITLE
Not compatible with IE 11.

### ISSUE THREAD

**Issue by tajinder89** [harshzalavadiya/react-multi-select-component#278]

**Comment by tajinder89** [comment]
I was trying to implement this library it is working fine with firefox/edge/Chrome/safari but it is not compatible with IE 11 because of both the dependencies (rooks and goober) used. Is it possible to fix it??

**Comment by harshzalavadiya** [comment]
@tajinder89 

There's no official IE11 support added for this module but if you are determined to do so then you can try below things and it _might_ work

- You can change target in `tsconfig.json` and try recompiling module to target ES2015
- [CSS variables are not supported in IE11 on which our style relies upon](https://github.com/harshzalavadiya/react-multi-select-component/issues/26#issuecomment-628637160)

Closing this since as of now there are no plan to directly support IE
