### ISSUE TITLE
Prop to remove close icon

### ISSUE THREAD

**Issue by guido-visser** [harshzalavadiya/react-multi-select-component#291]
Great work on the new releases!

I recently upgraded and I noticed that you've added a clear icon. Nice! However, I'd like to see an option to remove the X from the component, since I've created a small wrapper that clears the input. 

I tried to use `CloseIcon={null}` but that doesn't remove the close icon.

To be consistent with the current API, you could create a prop called: `hideCloseIcon` as a boolean. Render it when that prop is not present on the component.

**Comment by harshzalavadiya** [comment]
@guido-visser Thanks for the PR and issue but I guess you are using wrong prop it's `ClearIcon` not `CloseIcon`

Since I only check for truthy value `null` won't work but there's easy fix for this you can either use `<div/>` or `<React.Fragment/>` that will pass as truthy value and this will keep it minimal

p.s. I'll think about having seprate prop in future but as of now this keeps bundle size tiny closing, but PR's are always welcome :)
