### ISSUE TITLE
CodeSandBox example not working

### ISSUE THREAD

**Issue by bobaekang** [harshzalavadiya/react-multi-select-component#43]
Thanks for creating a great multi-select component!

Unfortunately, [the CodeSandBox example](https://codesandbox.io/s/react-multi-select-example-uqtgs) seems to be failing to render with error message: "SyntaxError: export declarations may only appear at top level of a module".

See the following screenshot for details.

![image](https://user-images.githubusercontent.com/22449454/83422552-52ce8980-a3ef-11ea-9174-78f8c00f35c1.png)

This may not be the component's fault since it (v2.0.8) works just fine for a React app I'm working on. But the CodeSandBox example failing makes it difficult for (potential) users to quickly check it out on the browser.

**Comment by harshzalavadiya** [comment]
hi @bobaekang,

Thanks for reporting this, this used to work fine some days before, problem is originating from one of the dependency I have filed [issue](https://github.com/cristianbote/goober/issues/149) package's repository

meanwhile you can use stackblitz instead of CSB here's starter example https://stackblitz.com/edit/react-7yn3vq

**Comment by bobaekang** [comment]
Thank you for your response! I'll close this issue since you're already working on it.

**Comment by harshzalavadiya** [comment]
Issue is resolved now codesandboxes should work as expected
