### ISSUE TITLE
I'll gate the  same dropdown but support for a single and multi select both so you have a solution for that

### ISSUE THREAD

**Issue by vc-akashkadia** [harshzalavadiya/react-multi-select-component#80]

**Comment by harshzalavadiya** [comment]
Hi @vc-akashkadia 

I didn't got your point completely, as of v3.x There's no support for single select since I would encourage to use pure native HTML component or if you are looking for more feature-rich solution use react-select instead

I would like to add single select in future maybe in a next major release but there's no addition planned as of now, but PR's are always welcome

**Comment by vc-akashkadia** [comment]
Ok, Thank's for the replay😊
________________________________
